"""add search indexes

Revision ID: 2786635ffd08
Revises: e2e703af0186
Create Date: 2026-07-27 17:58:35.267224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2786635ffd08'
down_revision: Union[str, Sequence[str], None] = 'e2e703af0186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_content_type', 'documents', ['content_type'], unique=False)
    op.create_index('ix_documents_ocr_status', 'documents', ['ocr_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_ocr_status', table_name='documents')
    op.drop_index('ix_documents_content_type', table_name='documents')
    # ### end Alembic commands ###
