"""add document indexes

Revision ID: 5b67a02cb143
Revises: ad5ae8973932
Create Date: 2026-07-26 14:22:39.703057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b67a02cb143'
down_revision: Union[str, Sequence[str], None] = 'ad5ae8973932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_filename', 'documents', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_filename', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    # ### end Alembic commands ###
