"""add file_hash to documents

Revision ID: a22e782c5cdb
Revises: 85a8f2467353
Create Date: 2026-07-26 18:59:14.853261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22e782c5cdb'
down_revision: Union[str, Sequence[str], None] = '85a8f2467353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'documents', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
