"""Add OCR fields to document

Revision ID: e234017be01e
Revises: a22e782c5cdb
Create Date: 2026-07-26 22:18:33.546692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e234017be01e'
down_revision: Union[str, Sequence[str], None] = 'a22e782c5cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('ocr_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ocr_completed_at')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'ocr_status')
    # ### end Alembic commands ###
