"""add document metadata fields

Revision ID: e2e703af0186
Revises: e234017be01e
Create Date: 2026-07-27 14:10:18.935876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e703af0186'
down_revision: Union[str, Sequence[str], None] = 'e234017be01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('line_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('paragraph_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'paragraph_count')
    op.drop_column('documents', 'line_count')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###
